import { StyleSheet } from '@react-pdf/renderer';

export const pdfStyles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    fontSize: 11,
    lineHeight: 1.5,
    color: '#1a1a2e',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: '#192C57',
  },
  logoSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  logo: {
    width: 48,
    height: 48,
  },
  titleBlock: {},
  mainTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#192C57',
    margin: 0,
    fontFamily: 'Helvetica',
  },
  subtitle: {
    fontSize: 11,
    color: '#6b7280',
    margin: 4,
    fontFamily: 'Helvetica',
  },
  ticketId: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#CBAE2D',
    fontFamily: 'Courier',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#192C57',
    marginBottom: 10,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e4e9',
    fontFamily: 'Helvetica',
  },
  fieldRow: {
    flexDirection: 'row',
    marginBottom: 8,
    gap: 12,
  },
  fieldLabel: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    minWidth: 100,
    fontFamily: 'Helvetica',
  },
  fieldValue: {
    fontSize: 11,
    color: '#1a1a2e',
    flex: 1,
    fontFamily: 'Helvetica',
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    fontSize: 9,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  priorityBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    fontSize: 9,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  description: {
    fontSize: 11,
    color: '#1a1a2e',
    lineHeight: 1.6,
    whiteSpace: 'pre-wrap',
    fontFamily: 'Helvetica',
  },
  timeline: {
    marginTop: 12,
  },
  timelineItem: {
    flexDirection: 'row',
    marginBottom: 12,
    paddingLeft: 16,
    borderLeftWidth: 2,
    borderLeftColor: '#e2e4e9',
    position: 'relative',
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    position: 'absolute',
    left: -6,
    top: 2,
  },
  timelineContent: {
    flex: 1,
    paddingLeft: 8,
  },
  timelineTime: {
    fontSize: 9,
    color: '#9ca3af',
    marginBottom: 2,
    fontFamily: 'Helvetica',
  },
  timelineStatus: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#1a1a2e',
    marginBottom: 2,
    fontFamily: 'Helvetica',
  },
  timelineNote: {
    fontSize: 10,
    color: '#6b7280',
    fontFamily: 'Helvetica',
  },
  comment: {
    marginBottom: 16,
    padding: 12,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
  },
  commentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  commentAuthor: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#192C57',
    fontFamily: 'Helvetica',
  },
  commentTime: {
    fontSize: 9,
    color: '#9ca3af',
    fontFamily: 'Helvetica',
  },
  commentMessage: {
    fontSize: 10,
    color: '#1a1a2e',
    lineHeight: 1.5,
    fontFamily: 'Helvetica',
  },
  footer: {
    marginTop: 32,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#e2e4e9',
    textAlign: 'center',
    fontSize: 9,
    color: '#9ca3af',
    fontFamily: 'Helvetica',
  },
  signatureLine: {
    marginTop: 40,
    borderTopWidth: 1,
    borderTopColor: '#192C57',
    width: '40%',
  },
  signatureLabel: {
    fontSize: 9,
    color: '#6b7280',
    marginTop: 4,
    fontFamily: 'Helvetica',
  },
  // Report-specific styles
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 24,
  },
  statCard: {
    flex: 1,
    minWidth: 120,
    padding: 16,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e4e9',
  },
  statValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#192C57',
    textAlign: 'center',
    fontFamily: 'Helvetica',
  },
  statLabel: {
    fontSize: 10,
    color: '#6b7280',
    textAlign: 'center',
    marginTop: 4,
    fontFamily: 'Helvetica',
  },
  table: {
    width: '100%',
    marginBottom: 16,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#192C57',
    color: 'white',
    padding: 8,
    fontSize: 9,
    fontWeight: 'bold',
    fontFamily: 'Helvetica',
  },
  tableRow: {
    flexDirection: 'row',
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e4e9',
    fontSize: 9,
    fontFamily: 'Helvetica',
  },
  tableCell: {
    flex: 1,
    paddingHorizontal: 4,
  },
  chartPlaceholder: {
    height: 200,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e4e9',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export const statusColors: Record<string, { bg: string; text: string }> = {
  OPEN: { bg: '#192C57', text: '#ffffff' },
  ASSIGNED: { bg: '#CBAE2D', text: '#1a1a2e' },
  IN_PROGRESS: { bg: '#0693e3', text: '#ffffff' },
  RESOLVED: { bg: '#00d084', text: '#1a1a2e' },
  CLOSED: { bg: '#6b7280', text: '#ffffff' },
  REOPENED: { bg: '#ff6900', text: '#ffffff' },
};

export const priorityColors: Record<string, { bg: string; text: string }> = {
  LOW: { bg: '#6b7280', text: '#ffffff' },
  MEDIUM: { bg: '#0693e3', text: '#ffffff' },
  HIGH: { bg: '#ff6900', text: '#ffffff' },
  CRITICAL: { bg: '#cf2e2e', text: '#ffffff' },
};